#ifndef AIRFRAME_H
#define AIRFRAME_H

#define SERVOS_DEFAULT_NB 7
#include "actuators_pwm_arch.h"
#define actuators actuators_pwm_values	//added

#define SERVO_AILEVON_LEFT 4
#define SERVO_AILEVON_LEFT_NEUTRAL 1500
#define SERVO_AILEVON_LEFT_TRAVEL_UP 0.0520833333333
#define SERVO_AILEVON_LEFT_TRAVEL_UP_NUM (100)
#define SERVO_AILEVON_LEFT_TRAVEL_UP_DEN (256)
#define SERVO_AILEVON_LEFT_TRAVEL_DOWN 0.0520833333333
#define SERVO_AILEVON_LEFT_TRAVEL_DOWN_NUM (100)
#define SERVO_AILEVON_LEFT_TRAVEL_DOWN_DEN (256)
#define SERVO_AILEVON_LEFT_MAX 2000
#define SERVO_AILEVON_LEFT_MIN 1000

#define SERVO_AILEVON_RIGHT 5
#define SERVO_AILEVON_RIGHT_NEUTRAL 1500
#define SERVO_AILEVON_RIGHT_TRAVEL_UP 0.0520833333333
#define SERVO_AILEVON_RIGHT_TRAVEL_UP_NUM (100)
#define SERVO_AILEVON_RIGHT_TRAVEL_UP_DEN (256)
#define SERVO_AILEVON_RIGHT_TRAVEL_DOWN 0.0520833333333
#define SERVO_AILEVON_RIGHT_TRAVEL_DOWN_NUM (100)
#define SERVO_AILEVON_RIGHT_TRAVEL_DOWN_DEN (256)
#define SERVO_AILEVON_RIGHT_MAX 2000
#define SERVO_AILEVON_RIGHT_MIN 1000

#define COMMAND_ROLL 0
#define COMMAND_PITCH 1
#define COMMAND_YAW 2
#define COMMAND_THRUST 3
#define COMMAND_RC_MODE 4
#define COMMAND_RC_ROLL 5
#define COMMAND_RC_PITCH 6
#define COMMAND_RC_THRUST 7
#define COMMAND_CAMERA 8
#define COMMANDS_NB 9
#define COMMANDS_FAILSAFE {0,0,0,0,0,0,0,0,0}

#define SERVO_AILEVON_RIGHT_IDX 1
#define Set_AILEVON_RIGHT_Servo(_v) { \
  actuators[SERVO_AILEVON_RIGHT_IDX] = Chop(_v, SERVO_AILEVON_RIGHT_MIN, SERVO_AILEVON_RIGHT_MAX); \
  ActuatorDefaultSet(SERVO_AILEVON_RIGHT, actuators[SERVO_AILEVON_RIGHT_IDX]); \
}

#define SERVO_AILEVON_LEFT_IDX 3
#define Set_AILEVON_LEFT_Servo(_v) { \
  actuators[SERVO_AILEVON_LEFT_IDX] = Chop(_v, SERVO_AILEVON_LEFT_MIN, SERVO_AILEVON_LEFT_MAX); \
  ActuatorDefaultSet(SERVO_AILEVON_LEFT, actuators[SERVO_AILEVON_LEFT_IDX]); \
}

#define SUPERVISION_NB_MOTOR 4

#define SECTION_STABILIZATION_ATTITUDE 1
#define STABILIZATION_ATTITUDE_SP_MAX_PHI RadOfDeg(90.)
#define STABILIZATION_ATTITUDE_SP_MAX_THETA RadOfDeg(90.)
#define STABILIZATION_ATTITUDE_SP_MAX_PSI RadOfDeg(45.)
#define STABILIZATION_ATTITUDE_SP_MAX_R RadOfDeg(90.)
#define STABILIZATION_ATTITUDE_SP_MAX_P RadOfDeg(90.)
#define STABILIZATION_ATTITUDE_DEADBAND_R 250
#define STABILIZATION_ATTITUDE_DEADBAND_A 250
#define STABILIZATION_ATTITUDE_REF_OMEGA_R RadOfDeg(600)
#define STABILIZATION_ATTITUDE_REF_ZETA_R 0.90
#define STABILIZATION_ATTITUDE_REF_MAX_R RadOfDeg(400.)
#define STABILIZATION_ATTITUDE_REF_MAX_RDOT RadOfDeg(8000.)
#define STABILIZATION_ATTITUDE_REF_OMEGA_Q RadOfDeg(800)
#define STABILIZATION_ATTITUDE_REF_ZETA_Q 0.90
#define STABILIZATION_ATTITUDE_REF_MAX_Q RadOfDeg(500.)
#define STABILIZATION_ATTITUDE_REF_MAX_QDOT RadOfDeg(8000.)
#define STABILIZATION_ATTITUDE_REF_OMEGA_P RadOfDeg(600)
#define STABILIZATION_ATTITUDE_REF_ZETA_P 0.85
#define STABILIZATION_ATTITUDE_REF_MAX_P RadOfDeg(220.)
#define STABILIZATION_ATTITUDE_REF_MAX_PDOT RadOfDeg(1800.)

#define SECTION_INS 1
#define INS_BARO_SENS 3.3
#define INS_BARO_SENS_NUM 33
#define INS_BARO_SENS_DEN 10

#define SECTION_AHRS 1
//#define AHRS_PROPAGATE_FREQUENCY 512
#define AHRS_PROPAGATE_FREQUENCY 1000
#define AHRS_MAG_UPDATE_YAW_ONLY 1
#define AHRS_H_X  0.47577
#define AHRS_H_Y  0.11811
#define AHRS_H_Z  0.87161

#endif // AIRFRAME_H
